---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by apple.
--- DateTime: 2018/8/26 上午12:56
---

Dwarf = Class("Dwarf")

function Dwarf:init(x,y,opts)
    GameObject.init(self,x,y,opts)
    local pid = self.pid or 1
    self.img = tile(pid)
end

function Dwarf:update(dt)

end

function Dwarf:draw()
    love.graphics.draw(tileset_img,self.img,self.x,self.y)
end

return Dwarf