---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by apple.
--- DateTime: 2018/8/26 上午12:56
---
Dwarf = Class("Dwarf")

function Dwarf:init(x,y,opts)
    GameObject.init(self,x,y,opts)
    local pid = self.pid or 1
    self.gx = math.floor(x/32) --- grid_x
    self.gy = math.floor(y/32) --- grid_y
    self.gz = 0
    self.ax = 0  --- add grid_x by ax
    self.ay = 0
    self.az = 0  --- z level

    self.look = love.math.random()
    self.feel = love.math.random()
    self.hear = love.math.random()
    self.img = tile(pid)
    self.state = {}
    self.message = {}
    self.map = {}
end

function Dwarf:update(dt)
    self.state = {
        "gx = " .. self.gx,
        "gy = " .. self.gy,
        "gz = " .. self.gz,
        "map = " .. self.map.biome,
        "floor = " .. self:getMapFloor()
    }
    --- TODO 将UI与人物属性联系起来
    self.message = {
        "看到" .. self.look,
        "感觉" .. self.feel,
        "听见" .. self.hear
    }
end

--- TODO 考虑将UI 放到这里

function Dwarf:draw()
    love.graphics.draw(tileset_img,self.img,self.x,self.y)
    love.graphics.print(table.concat(self.state," "))
    love.graphics.print(table.concat(self.message,"\n"),1000)
end

function Dwarf:keypressed(key,isrepeat)
    if key == "right" then
        self:move(1,0)
    elseif key == "left" then
        self:move(-1,0)
    end
    if key == "up" then
        self:move(0,-1)
    elseif key == "down" then
        self:move(0,1)
    end
    return self.x,self.y
end

function Dwarf:setMap(map)
    self.map = map
end

function Dwarf:move(ax,ay)
    self.gx = self.gx + ax
    self.gy = self.gy + ay
    self.x = self.gx * 32
    self.y = self.gy * 32
end

function Dwarf:getMapFloor()
    if self.map[self.gx] and self.map[self.gx][self.gy] then
        local floor = self.map[self.gx][self.gy].floor
        local floorName = ""
        return floor
    end
    return -1
end

function Dwarf:rampUp()
    self.gz = self.gz + 1
end

function Dwarf:rampDow()
    self.gz = self.gz -1
end

return Dwarf