---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by apple.
--- DateTime: 2018/8/26 上午12:38
---
--- @class GameObject

local GameObject = Class("GameObject")

--- @param opts table

function GameObject:init(x,y,opts)
    self.x = x
    self.y = y
    if opts then
        for k, v in pairs(opts) do
            self[k] = v
        end
    end
    self.dead = false
end

function GameObject:update(dt)

end

function GameObject:draw()
    love.graphics.print(self.type,self.x,self.y)
end

return GameObject