---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by apple.
--- DateTime: 2018/8/27 下午6:52
---

LocalMap = Class("LocalMap",GameObject)

function LocalMap:init(x,y,opts)
    GameObject.init(self,x,y,opts)
    self.biome = opts.biome or "Mountain"
    self.elevation = opts.elevation
end