---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by apple.
--- DateTime: 2018/8/26 下午11:54
---

local WorkShop = Class("WorkShop",GameObject)

function WorkShop:init()
    GameObject.init(self,x,y,opts)
    self.floor = {"floor_stone"}
    self.furniture = {
        "T T"   ,
        "TST"   ,
        " O "   ,
    }
    self.furniture_info = {
        T = {id = "table",pid = 0,name = "table"},
        S = {id = "status",pid = 0,name = "status"},
        O = {id = "stone",pid = 0,name = "stone"},
    }
    self.aoe = {
        {-1, 1},{0, 1},{1, 1},
        {-1, 0},{0, 0},{1, 0},
        {-1,-1},{0,-1},{1,-1}
    }
end

function WorkShop:mapSpaceCanPlace(builder,map)
    local ox,oy,oz = builder.gx,builder.gy,builder.gz
    for _, v in ipairs(self.aoe) do
        local px,py = v[1] + ox,v[2] + oy
        if map[px][py].gz ~= builder.gz then
            return false
        end
    end
    return true
end

function WorkShop:setBluePrint(builder,map)
    if self:mapSpaceCanPlace(builder,map) then
        local ox,oy,oz = builder.gx,builder.gy,builder.gz
        for _, v in ipairs(self.aoe) do
            local px,py = v[1] + ox,v[2] + oy
            map[px][py].floor = self.floor
            map[px][py].furniture = self.furniture[v1][v2]
            map[px][py].wall = "workshop"
        end
        return true
    end
end


return WorkShop