---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by apple.
--- DateTime: 2018/8/26 上午12:56
---
--require("GameObject")

Dwarf = GameObject:extend()

function Dwarf:new(area,x,y,opts)
    Dwarf.super.new(self,area,x,y,opts)
    self.pid = opts.pid or 1
    self.gx = math.floor(x/32) --- grid_x
    self.gy = math.floor(y/32) --- grid_y
    self.gz = 0
    self.ax = 0  --- add grid_x by ax
    self.ay = 0
    self.az = 0  --- z level

    self.look = love.math.random()
    self.feel = love.math.random()
    self.hear = love.math.random()
    self.tile = Tiled(self.pid,opts)
    self.state = {}
    self.message = {}
    self.map = {}

end

function Dwarf:update(dt)
    Dwarf.super.update(self,dt)
    if input:pressed("left")    then  self:move(-1,0)   end
    if input:pressed("right")   then  self:move(1,0)    end
    if input:pressed("up")      then  self:move(0,-1)   end
    if input:pressed("down")    then  self:move(0,1)    end


    self.state = {
        "gx = " .. self.gx,
        "gy = " .. self.gy,
        "gz = " .. self.gz,
        --"map = " .. self.map.biome,
        "floor = " .. self:getMapFloor()
    }
    --- TODO 将UI与人物属性联系起来
    self.message = {
        "看到" .. self.look,
        "感觉" .. self.feel,
        "听见" .. self.hear
    }
end

--- TODO 考虑将UI 放到这里

function Dwarf:draw()
    GUI.box(0,0,1080,32)
    GUI.box(1080,0,200,300)
    GUI.box(0,32,32,656)
    GUI.box(0,688,1080,32)
    self.tile:draw(self.x,self.y)

    love.graphics.print(table.concat(self.state," "))
    love.graphics.print(table.concat(self.message,"\n"),1080)
end

function Dwarf:setMap(map)
    self.map = map
end

function Dwarf:move(ax,ay)
    self.gx = self.gx + ax
    self.gy = self.gy + ay

    --self.timer:tween(1,self,{gx = self.gx + ax,gy = self.gy + ay},'linear')
    self.x = self.gx * 32
    self.y = self.gy * 32
end

function Dwarf:getMapFloor()
    if self.map[self.gx] and self.map[self.gx][self.gy] then
        local floor = self.map[self.gx][self.gy].floor
        local floorName = ""
        return floor
    end
    return -1
end

function Dwarf:rampUp()
    self.gz = self.gz + 1
end

function Dwarf:rampDow()
    self.gz = self.gz -1
end

return Dwarf