---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by apple.
--- DateTime: 2018/8/26 上午12:38
---
--- @class GameObject

GameObject = Object:extend()

function GameObject:new(area,x,y,opts)
	local opts = opts or {}
    if opts then for k, v in pairs(opts) do self[k] = v end end

    self.area = area
    self.x = x
    self.y = y
    self.id = UUID()
    self.dead = false
    self.timer = Timer()
end

function GameObject:update(dt)
    if self.collider then self.x,self.y = self.collider:getPosition() end
	if self.timer then self.timer:update(dt) end
end

function GameObject:draw()
	-- love.graphics.rectangle("fill",self.x,self.y,45,45)
end

function GameObject:destroy()
    self.timer:destroy()
    if self.collider then self.collider:destroy() end
    self.collider = nil
end

return GameObject