---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by apple.
--- DateTime: 2018/8/25 下午11:37
---
Grass = GameObject:extend()

function Grass:new(area,x,y,opts)
    Grass.super.new(self,area,x,y,opts)
    self.tiled = Tiled(3,opts)
end


function Grass:draw()
    self.tiled:draw()
end