---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by apple.
--- DateTime: 2018/8/25 下午11:37
---
Grass = Object:extend()

function Grass.new(x,y,opts)
    self.x = x
    self.y = y
    if opts then
        for k, v in pairs(opts) do
            self[k] = v
        end
    end
    self.dead = false
end