---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by apple.
--- DateTime: 2018/8/27 下午6:52
---

LocalMap = Object:extend()

function LocalMap:new(x,y,opts)
    LocalMap.super.new(self,x,y,opts)
    self.biome = opts.biome or "Mountain"
    self.elevation = opts.elevation
end