---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by apple.
--- DateTime: 2018/9/2 上午11:48
---

Tiled = Object:extend()

function Tiled:new(pid,opts)
    local opts = opts or {}
    self.img = opts.img or tileset_img
    self.tile_size = opts.tile_size or 32
    self.pid = pid
    self.quad = self:quad()
end


function Tiled:quad()
    local pid = self.pid or 0
    local width,height = self.img:getWidth(),self.img:getHeight()
    local w,h = width/self.tile_size, height/self.tile_size
    local x,y = math.floor(pid%w)*32,math.floor(pid/w)*32
    local quad = love.graphics.newQuad(x, y, 32,32,width, height)
    return quad
end

function Tiled:draw(x,y)
    local x,y = x,y or 0,0
    love.graphics.draw(self.img,self.quad,x,y)
end