---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by apple.
--- DateTime: 2018/8/26 上午12:52
---

return {
    --{id = "plant1",name = "grass", pid = {23,130,147,244}},
    --{id = "plant2",name = "seed", pid = 129},
    --{id = "plant3",name = ""},
    {id = "plant001" ,pid= 23,name = "Bentgrass",name_cn = "四季青"},
    {id = "plant002" ,pid= 89,name = "Cloudberry",name_cn = "云莓"},
    {id = "plant003" ,pid= 130,name = "Cottongrass",name_cn = "羊胡子草"},
    {id = "plant004" ,pid= 244,name = "Fescue grass",name_cn = "狐尾草"},
    {id = "plant005" ,pid= 252,name = "Hair grass",name_cn = "南极发草"},
    {id = "plant006" ,pid= 147,name = "Meadow grass",name_cn = "草熟"},
    {id = "plant007" ,pid= 238,name = "Mountain avens",name_cn = "三叶水杨梅"},
    {id = "plant008" ,pid= 80,name = "White mountain heather",name_cn = "灰叶欧石楠"},
}