---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by apple.
--- DateTime: 2018/8/25 下午11:03
---

function love.conf(t)
    t.title = "矮人冒险"
    t.window.width = 1280
    t.window.height = 720
end