---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by apple.
--- DateTime: 2018/8/25 下午11:03
---

io.stdout:setvbuf("no")

gw = 640
gh = 360
sw = 2
sh = 2
function love.conf(t)
    t.title = "矮人冒险"
    t.window.width = gw*sw
    t.window.height = gh*sh
end